// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUddqSK05_ClzL172tV836aUm1gG9rrE8',
    appId: '1:665911330613:web:25c34ff5abb81bd4e92e7c',
    messagingSenderId: '665911330613',
    projectId: 'kaskita-c269a',
    authDomain: 'kaskita-c269a.firebaseapp.com',
    storageBucket: 'kaskita-c269a.firebasestorage.app',
    measurementId: 'G-B5N75FFQWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANJVzX52gAcfGoLGlW9BFOtLfjOfhDVXQ',
    appId: '1:665911330613:android:b364e0a8cec3d51ee92e7c',
    messagingSenderId: '665911330613',
    projectId: 'kaskita-c269a',
    storageBucket: 'kaskita-c269a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBImWxOW_TMIUM5vJMc9rXfa3XRKBz4vw8',
    appId: '1:665911330613:ios:1ef45e574d6063a3e92e7c',
    messagingSenderId: '665911330613',
    projectId: 'kaskita-c269a',
    storageBucket: 'kaskita-c269a.firebasestorage.app',
    iosBundleId: 'com.example.kaskita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBImWxOW_TMIUM5vJMc9rXfa3XRKBz4vw8',
    appId: '1:665911330613:ios:1ef45e574d6063a3e92e7c',
    messagingSenderId: '665911330613',
    projectId: 'kaskita-c269a',
    storageBucket: 'kaskita-c269a.firebasestorage.app',
    iosBundleId: 'com.example.kaskita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUddqSK05_ClzL172tV836aUm1gG9rrE8',
    appId: '1:665911330613:web:1be69698a0fb5f68e92e7c',
    messagingSenderId: '665911330613',
    projectId: 'kaskita-c269a',
    authDomain: 'kaskita-c269a.firebaseapp.com',
    storageBucket: 'kaskita-c269a.firebasestorage.app',
    measurementId: 'G-5FYT5JL1HN',
  );
}
